# Generated by Django 3.1.7 on 2021-04-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_elemento', models.AutoField(primary_key=True, serialize=False)),
                ('numero_serie', models.CharField(max_length=20)),
                ('cantidad_elemetos', models.IntegerField()),
                ('precio', models.FloatField()),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
    ]
