# Generated by Django 3.1.7 on 2021-04-06 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventario',
            table='inventario_inventario',
        ),
    ]
